Preloader Functionality Added
hash-define-organization/Hash-Whiteboard pull request #25
Opened 2022-03-04 04:45 UTC by shreya024

I have added Preloader functionality.
Referring to issue number #17

2022-03-04 08:28 UTC, DhairyaBahl commented
@shreya024 Well done but That continuous scale on the logo is not looking as expected. How about just a logo in the middle of the screen. Remove the `HASH DEFINE` that you wrote below the image. and add a horizontal loading bar below the image. Hope you are getting my point.

2022-03-04 11:24 UTC, shreya024 commented
> @shreya024 Well done but That continuous scale on the logo is not looking as expected. How about just a logo in the middle of the screen. Remove the `HASH DEFINE` that you wrote below the image. and add a horizontal loading bar below the image. Hope you are getting my point.

Kindly check now .I have removed the text and added a horizontal loading bar but kept the animation.

2022-03-04 16:19 UTC, vedant-jain03 requested changes

2022-03-04 16:19 UTC, vedant-jain03 commented on src/Components/Preloader/Preloader.scss
> +    height: 40px;
Kindly make `height: 20px`

2022-03-04 16:20 UTC, vedant-jain03 commented
Please uncommit `package-lock.json` file.

2022-03-05 12:49 UTC, vedant-jain03 approved these changes

2022-03-05 12:51 UTC, vedant-jain03 commented
Good work @shreya024

2022-03-05 12:52 UTC, merged