added the warning modal
hash-define-organization/Hash-Whiteboard pull request #39
Opened 2022-03-09 13:46 UTC by KamalSinghKhanna

Added Warning Modal to ask for confirmation before clearing the board completely.
Fixes #11

2022-03-14 07:51 UTC, vedant-jain03 requested changes

2022-03-14 07:51 UTC, vedant-jain03 commented on src/Components/Modal/Modal.js
> +
Remove extra lines

2022-03-14 07:51 UTC, vedant-jain03 commented on src/Components/Modal/modal.css
> +    width: 70px;
The design looks so simple, kindly enhance it.
Functionality LGTM
Kindly work on UI for Modal.

2022-03-23 06:42 UTC, KamalSinghKhanna commented
Sorry for late response @vedant-jain03, I am busy with my exams now days, but I will try to implement changes as you have suggested.

2022-06-16 06:19 UTC, closed without merging